/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResearcherRouteImport } from './routes/researcher'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearcherSearchRouteImport } from './routes/researcher.search'
import { Route as DemoChartRouteImport } from './routes/demo.chart'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearcherRoute = ResearcherRouteImport.update({
  id: '/researcher',
  path: '/researcher',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearcherSearchRoute = ResearcherSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ResearcherRoute,
} as any)
const DemoChartRoute = DemoChartRouteImport.update({
  id: '/demo/chart',
  path: '/demo/chart',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/researcher': typeof ResearcherRouteWithChildren
  '/signup': typeof SignupRoute
  '/demo/chart': typeof DemoChartRoute
  '/researcher/search': typeof ResearcherSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/researcher': typeof ResearcherRouteWithChildren
  '/signup': typeof SignupRoute
  '/demo/chart': typeof DemoChartRoute
  '/researcher/search': typeof ResearcherSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/researcher': typeof ResearcherRouteWithChildren
  '/signup': typeof SignupRoute
  '/demo/chart': typeof DemoChartRoute
  '/researcher/search': typeof ResearcherSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/login'
    | '/researcher'
    | '/signup'
    | '/demo/chart'
    | '/researcher/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/researcher'
    | '/signup'
    | '/demo/chart'
    | '/researcher/search'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/login'
    | '/researcher'
    | '/signup'
    | '/demo/chart'
    | '/researcher/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  ResearcherRoute: typeof ResearcherRouteWithChildren
  SignupRoute: typeof SignupRoute
  DemoChartRoute: typeof DemoChartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researcher': {
      id: '/researcher'
      path: '/researcher'
      fullPath: '/researcher'
      preLoaderRoute: typeof ResearcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researcher/search': {
      id: '/researcher/search'
      path: '/search'
      fullPath: '/researcher/search'
      preLoaderRoute: typeof ResearcherSearchRouteImport
      parentRoute: typeof ResearcherRoute
    }
    '/demo/chart': {
      id: '/demo/chart'
      path: '/demo/chart'
      fullPath: '/demo/chart'
      preLoaderRoute: typeof DemoChartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResearcherRouteChildren {
  ResearcherSearchRoute: typeof ResearcherSearchRoute
}

const ResearcherRouteChildren: ResearcherRouteChildren = {
  ResearcherSearchRoute: ResearcherSearchRoute,
}

const ResearcherRouteWithChildren = ResearcherRoute._addFileChildren(
  ResearcherRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  ResearcherRoute: ResearcherRouteWithChildren,
  SignupRoute: SignupRoute,
  DemoChartRoute: DemoChartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
