# Generated by Django 5.1.3 on 2026-03-15 06:56

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


def _add_ivfflat_index(apps, schema_editor):
    """Create IvfflatIndex — no-op on non-PostgreSQL backends."""
    if schema_editor.connection.vendor != "postgresql":
        return
    Chunk = apps.get_model("embeddings", "Chunk")
    index = pgvector.django.indexes.IvfflatIndex(
        fields=["embedding"],
        name="chunk_embedding_ivfflat_idx",
    )
    schema_editor.add_index(Chunk, index)


def _remove_ivfflat_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute('DROP INDEX IF EXISTS "chunk_embedding_ivfflat_idx"')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embeddings', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('source', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='embeddings.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        # IvfflatIndex is PostgreSQL-specific; use SeparateDatabaseAndState so
        # the migration state tracks it (required for 0003's RemoveIndex) while
        # the actual database operation is skipped on SQLite.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="chunk",
                    index=pgvector.django.indexes.IvfflatIndex(
                        fields=["embedding"],
                        name="chunk_embedding_ivfflat_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(_add_ivfflat_index, _remove_ivfflat_index),
            ],
        ),
    ]
