# Generated by Django 5.1.3 on 2026-03-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0003_alter_chunk_embedding_hnsw'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
